# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('app-install', ['core'])
    module.source = [
        'model/app-install.cc',
        'helper/app-install-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('app-install')
    module_test.source = [
        'test/app-install-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'app-install'
    headers.source = [
        'model/app-install.h',
        'helper/app-install-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

