# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('app-install-example', ['app-install'])
    obj.source = 'app-install-example.cc'

