# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('parameters', ['core'])
    module.source = [
        'model/parameters.cc',
        'helper/parameters-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('parameters')
    module_test.source = [
        'test/parameters-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'parameters'
    headers.source = [
        'model/parameters.h',
        'helper/parameters-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

